 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Players;
import java.awt.HeadlessException;

import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.objects.NativeRegExp;

/**
 *
 * @author Kobem
 */
public class Login extends javax.swing.JFrame {

    Players player = new Players();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenTablero = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnlPanelPrincipal = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblImagenOthello = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnOnePlayer = new javax.swing.JButton();
        btnTwoPlayers = new javax.swing.JButton();
        jBAyuda = new javax.swing.JButton();

        lblImagenTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/.I. 1.png"))); // NOI18N
        lblImagenTablero.setText("jLabel2");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPanelPrincipal.setBackground(new java.awt.Color(51, 102, 0));
        pnlPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setText("¡Bienvenido a Othello!");
        pnlPanelPrincipal.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 80, 30));

        lblImagenOthello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/.I. 1.png"))); // NOI18N
        pnlPanelPrincipal.add(lblImagenOthello, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 370, 280));

        btnLogin.setText("Registrarse");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, 30));

        btnOnePlayer.setText("Un jugador");
        btnOnePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnePlayerActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnOnePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        btnTwoPlayers.setText("Dos Jugadores");
        btnTwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoPlayersActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnTwoPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jBAyuda.setText("Ayuda");
        jBAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAyudaActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(jBAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        try {
            String name = JOptionPane.showInputDialog("Escriba su nombre");
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite un texto válido");
            } else {
                player = new Players();
                player.setName(name);
                player.onePlayer.add(player);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos para registrar");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnOnePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnePlayerActionPerformed
        Players playerOne = new Players();
        if (player.onePlayer.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay jugadores disponibles, regístrese");
        } else {
            String onePlayerName = JOptionPane.showInputDialog(null, "¿Cúal es su nombre?");
            if (onePlayerName.isEmpty() && onePlayerName != null) {
                playerOne.setName(onePlayerName);
                player.onePlayer.add(playerOne);
            }
            if (search1p(onePlayerName)) {
                JFOthelloPrincipal window = new JFOthelloPrincipal();
                window.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró su nombre");
            }
    }//GEN-LAST:event_btnOnePlayerActionPerformed
    }
    private void btnTwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoPlayersActionPerformed
        Players player1 = new Players();
        Players player2 = new Players();

        String input = JOptionPane.showInputDialog("Escriba su nombre");
        if (input.isEmpty() && input != null) {
            if (input.isEmpty() && input != null) {
                JOptionPane.showMessageDialog(null, "Digite un texto válido");
            } else {
                String onePlayerName = JOptionPane.showInputDialog("Escriba su nombre jugador 1");
                player1.setName(onePlayerName);
                String twoPlayerName = JOptionPane.showInputDialog("Escriba su nombre jugador 2");
                player2.setName(twoPlayerName);
                if (searchPlayer(onePlayerName, twoPlayerName)) {
                    JFOthelloPrincipal window = new JFOthelloPrincipal();
                    window.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontraron sus datos");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron sus datos");
        }
    }//GEN-LAST:event_btnTwoPlayersActionPerformed

    private void jBAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAyudaActionPerformed

        Help fichero = new Help(this, true);
        fichero.setVisible(true);


    }//GEN-LAST:event_jBAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOnePlayer;
    private javax.swing.JButton btnTwoPlayers;
    private javax.swing.JButton jBAyuda;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblImagenOthello;
    private javax.swing.JLabel lblImagenTablero;
    private javax.swing.JPanel pnlPanelPrincipal;
    // End of variables declaration//GEN-END:variables

    private boolean searchPlayer(String onePlayerName, String twoPlayerName) {
        for (int i = 0; i < player.twoPlayers.size(); i++) {
            if (player.twoPlayers.get(i).getName().equals(onePlayerName) && player.twoPlayers.get(i).getName().equals(twoPlayerName)) {
                return true;
            }
        }
        return false;
    }

    private boolean search1p(String onePlayerName) {
        for (int i = 0; i < player.onePlayer.size(); i++) {
            if (player.onePlayer.get(i).getName().equals(onePlayerName)) {
                return true;
            }
        }
        return false;
    }

}
